# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - IIDXTierTable

on:
  push:
    branches:
      - main
    paths:
      - 'IIDXTierTable.Api/**'
      - '.github/workflows/main_iidxtiertable.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: azure-functions
  cancel-in-progress: true

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './IIDXTierTable.Api'
  DOTNET_VERSION: '10.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v7

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          dotnet restore '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/IIDXTierTable.Api.csproj'
          dotnet publish '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/IIDXTierTable.Api.csproj' \
            --configuration Release \
            --output '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output' \
            --no-restore
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'IIDXTierTable'
          sku: 'flexconsumption'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_985DE189E2E446449F5AD0655B3FB4AF }}